<div id="conPie" style="width:100%;height:100%">
    <div id="firma1" style="with:160px;height:35px;margin: 5px 5px 5px 150px; float:left;border:0px solid #000;"><div id="linea" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;">_________________</div><div id="nombre" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;font-size:10px;"><n class="fo">Recibe: Nombre y Firma<br>COSMETICA</n></div></div>
		<div id="firma2" style="with:160px;height:35px;margin: 40px 0px 5px 20px; float:left;border:0px solid #000;"><div id="linea" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;">_________________</div><div id="nombre" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;font-size:10px;"><n class="fo">Aprobaci&oacute;n: Nombre y Firma<br>ASEGURAMIENTO DE CALIDAD</n></div></div>
		<div id="firma3" style="with:160px;height:35px;margin: 5px 0px 5px 30px; float:left;border:0px solid #000;"><div id="linea" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;">_________________</div><div id="nombre" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;font-size:10px;"><n class="fo">Entrega: Nombre y Firma<br>INGENIERIA</n></div></div><br><br><br><br><br><br>
	
		<div id="firmas" style="margin:20px auto 0px auto;">
		<div id="firma1" style="with:160px;height:35px;margin: 5px 10px 5px 80px; float:left;border:0px solid #000;"><div id="linea" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;">_________________</div><div id="nombre" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;font-size:10px;">ELABOR&Oacute;<BR>Clara S&aacute;nchez Vel&aacute;zquez<br>Ejecutiva de Cuenta HP Scitex</div></div>
		<div id="firma2" style="with:160px;height:35px;margin: 5px auto 5px 80px; float:left;border:0px solid #000;"><div id="linea" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;">_________________</div><div id="nombre" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;font-size:10px;">REVIS&Oacute;<BR>Lic.Belinda D&iacute;az Trujillo<br>Responsable del SAC</div></div>
		<div id="firma3" style="with:160px;height:35px;margin: 5px auto 5px 80px; float:left;border:0px solid #000;"><div id="linea" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;">_________________</div><div id="nombre" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;font-size:10px;">AUTORIZ&Oacute;<BR>Lic.Humberto Galv&aacute;n Lassard<br>Subdirecci&oacute;n de Operaciones</div></div>
	        
			
	</div>
	        <br><br><br><div id="firma4" style="with:160px;height:35px;margin: 3px 10px 5px 80px; float:left;border:0px solid #000;"><br><div id="nombre" style="margin:2px auto 0 auto; clear:both:width:80%;text-align:center;font-size:10px;"><br>ESTE DOCUMENTO ES DE USO EXLCUSIVO DE IQ ELECTRONICS INTERNATIONAL, S.A. DE C.V.
		QUEDA ESTRICTAMENTE <br>PROHIBIDA SU REPRODUCCI&Oacute;N TOTAL O PARCIAL SIN AUTORIZACI&Oacute;N PREVIA</div></div><br>
</div>			