<?php
	session_start();
	$archivoConf="../../includes/txtApp".$_SESSION["nombreApp"].".php";	
	include($archivoConf);	
	unset($txtApp['session']['name']);	
	unset($txtApp['session']['nivelUsuario']);
	unset($txtApp['session']['loginUsuario']);
	unset($txtApp['session']['passwordUsuario']);
	unset($txtApp['session']['idUsuario']);
	unset($txtApp['session']['nombreUsuario']);
	unset($txtApp['session']['apellidoUsuario']);
	unset($txtApp['session']['origenSistemaUsuario']);
	unset($txtApp['session']['origenSistemaUsuarioNombre']);
	unset($txtApp['session']['cambiarPassUsuario']);
	unset($txtApp['session']['sexoUsuario']);
	unset($txtApp['session']['nominaUsuario']);
	unset($_SESSION["sistema"]);
	unset($_SESSION["nombreApp"]);	
	session_destroy();	
	header("Location: ../inicio/index.php");
	exit;
?>